"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/context/AuthContext";

import {
  FileText,
  Search,
  IndianRupee,
  Calendar,
  User,
  Printer,
  Loader2,
  Filter,
  CreditCard,
  ScanBarcode,
} from "lucide-react";
import { fetchCollectorBookings } from "@/lib/api";
import { QRCodeSVG } from "qrcode.react";

export default function ReceiptsPage() {
  const router = useRouter();
  const { user } = useAuth();

  // Protect page: Redirect processor roles to pending reports
  useEffect(() => {
    if (["processor", "sample_collector", "lab_collector", "lab_processor"].includes(user?.role)) {
      router.push("/lab/pending");
    }
  }, [user, router]);

  const [bookings, setBookings] = useState([]);

  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [collectorName, setCollectorName] = useState("");
  const [selectedBooking, setSelectedBooking] = useState(null);
  const [printMode, setPrintMode] = useState("receipt"); // 'receipt' or 'label'

  // Fetch collector's bookings on mount
  useEffect(() => {
    const loadBookings = async () => {
      // Get logged-in user details
      const userData = localStorage.getItem("user");
      let name = "Lab Staff";
      if (userData) {
        try {
          const user = JSON.parse(userData);
          if (user.name) name = user.name;
        } catch (e) {
          console.error("Failed to parse user data", e);
        }
      }
      setCollectorName(name);

      try {
        const data = await fetchCollectorBookings(name);
        if (data.success) {
          setBookings(data.bookings);
        }
      } catch (err) {
        console.error("Failed to fetch bookings:", err);
      } finally {
        setLoading(false);
      }
    };

    loadBookings();
  }, []);

  // Filter based on search query
  const filteredBookings = bookings.filter(
    (b) =>
      b.patientName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      b.receiptNo.toLowerCase().includes(searchQuery.toLowerCase()) ||
      b.sampleId.toLowerCase().includes(searchQuery.toLowerCase()),
  );

  const handlePrint = () => {
    setTimeout(() => window.print(), 100);
  };

  return (
    <div className="flex flex-col xl:flex-row gap-8 pb-20 print:p-0 print:pb-0 print:block">
      {/* List Section - Hidden on Print */}
      <div className="flex-1 space-y-6 print:hidden">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-black text-gray-900 tracking-tight">
              Receipt History
            </h2>
            <p className="text-sm font-medium text-gray-500 mt-1">
              View and reprint past receipts generated by you
            </p>
          </div>
          <div className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-200 rounded-lg text-sm font-bold text-gray-600 shadow-sm">
            <User className="w-4 h-4 text-gray-400" />
            {collectorName}
          </div>
        </div>

        {/* Search Bar */}
        <div className="relative group">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400 group-focus-within:text-gray-900 transition-colors" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search by Patient Name, Receipt No, or Sample ID..."
            className="w-full pl-12 pr-4 py-4 rounded-2xl bg-white border border-gray-200 focus:border-gray-900 focus:ring-0 text-gray-900 font-bold shadow-sm transition-all"
          />
          <div className="absolute right-4 top-1/2 -translate-y-1/2">
            <Filter className="w-5 h-5 text-gray-400" />
          </div>
        </div>

        {/* Bookings List */}
        <div className="bg-white border border-gray-200 shadow-sm overflow-hidden">
          {loading ? (
            <div className="flex items-center justify-center py-20">
              <Loader2 className="w-8 h-8 animate-spin text-gray-400" />
            </div>
          ) : filteredBookings.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-20 text-center">
              <FileText className="w-12 h-12 text-gray-200 mb-4" />
              <h3 className="text-lg font-bold text-gray-900">
                No Receipts Found
              </h3>
              <p className="text-sm text-gray-500 mt-1">
                You haven't generated any receipts yet.
              </p>
            </div>
          ) : (
            <div className="divide-y divide-gray-100">
              {filteredBookings.map((booking) => (
                <div
                  key={booking._id}
                  onClick={() => setSelectedBooking(booking)}
                  className={`p-6 hover:bg-gray-50 cursor-pointer transition-all border-b border-gray-100 last:border-0 ${
                    selectedBooking?._id === booking._id ? "bg-gray-50" : ""
                  }`}
                >
                  <div className="flex justify-between items-start mb-4">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 bg-gray-900 text-white flex items-center justify-center font-bold text-xs">
                        {booking.patientName.substring(0, 2).toUpperCase()}
                      </div>
                      <div>
                        <h4 className="font-bold text-gray-900 text-base">
                          {booking.patientName}
                        </h4>
                        <div className="flex items-center gap-2 text-xs font-bold text-gray-400 mt-1">
                          <span>{booking.receiptNo}</span>
                          <span>•</span>
                          <span>{booking.sampleId}</span>
                        </div>
                      </div>
                    </div>
                    <div className="text-right">
                      <span className="block text-lg font-black text-gray-900">
                        ₹{booking.totalAmount}
                      </span>
                      <span
                        className={`inline-flex items-center gap-1 text-[10px] uppercase font-black tracking-widest px-2 py-0.5 mt-1 ${
                          booking.paymentMode === "online"
                            ? "bg-green-100 text-green-700"
                            : "bg-gray-100 text-gray-600"
                        }`}
                      >
                        {booking.paymentMode === "online" ? (
                          <CreditCard className="w-3 h-3" />
                        ) : (
                          <IndianRupee className="w-3 h-3" />
                        )}
                        {booking.paymentMode || "Cash"}
                      </span>
                    </div>
                  </div>

                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-4 text-[11px] font-bold text-gray-500 uppercase tracking-wide">
                      <div className="flex items-center gap-1.5">
                        <Calendar className="w-3.5 h-3.5" />
                        {new Date(booking.createdAt).toLocaleDateString(
                          "en-IN",
                          {
                            day: "2-digit",
                            month: "short",
                            year: "numeric",
                          },
                        )}
                      </div>
                      <div className="flex items-center gap-1.5">
                        <FileText className="w-3.5 h-3.5" />
                        {booking.tests.length} Tests
                      </div>
                    </div>

                    <div className="flex gap-2">
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          setSelectedBooking(booking);
                          setPrintMode("receipt");
                        }}
                        className="p-2 bg-white border border-gray-200 hover:bg-gray-900 hover:text-white hover:border-gray-900 transition-colors"
                        title="View Receipt"
                      >
                        <Printer className="w-4 h-4" />
                      </button>
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          setSelectedBooking(booking);
                          setPrintMode("label");
                        }}
                        className="p-2 bg-white border border-gray-200 hover:bg-gray-900 hover:text-white hover:border-gray-900 transition-colors"
                        title="Print Label"
                      >
                        <ScanBarcode className="w-4 h-4" />
                      </button>
                    </div>
                  </div>

                  {selectedBooking?._id === booking._id && (
                    <div className="mt-4 pt-4 border-t border-gray-100 text-xs font-bold text-gray-900 flex items-center justify-center gap-2 bg-gray-50/50 py-2">
                      Previewing {printMode === "label" ? "Label" : "Receipt"}{" "}
                      <Printer className="w-3 h-3" />
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Preview & Print Section */}
      <div className="w-full xl:w-[450px] space-y-6 print:fixed print:inset-0 print:bg-white print:z-[50] print:h-screen print:flex print:items-start print:justify-center">
        {!selectedBooking ? (
          <div className="sticky top-24 h-[600px] border-2 border-dashed border-gray-200 rounded-[32px] flex flex-col items-center justify-center text-center p-8 bg-gray-50/50 print:hidden">
            <Printer className="w-16 h-16 text-gray-200 mb-6" />
            <h3 className="text-xl font-bold text-gray-400">
              Select a Receipt
            </h3>
            <p className="text-sm font-medium text-gray-400 mt-2 max-w-[200px]">
              Click on any booking from the list to view and reprint the
              receipt.
            </p>
          </div>
        ) : (
          <div className="sticky top-24 print:static print:w-full print:max-w-[80mm]">
            <div className="flex items-center justify-between mb-6 px-2 print:hidden">
              <h3 className="text-xs font-black uppercase tracking-widest text-gray-400">
                {printMode === "label" ? "Label Preview" : "Receipt Preview"}
              </h3>
              <button
                onClick={handlePrint}
                className="bg-gray-900 text-white text-xs font-bold px-4 py-2 rounded-lg flex items-center gap-2 hover:bg-black transition-all shadow-lg shadow-gray-200"
              >
                <Printer className="w-3.5 h-3.5" />
                Print Now
              </button>
            </div>

            {/* Thermal Receipt Layout */}
            {printMode === "receipt" && (
              <div
                className="bg-white rounded-none shadow-2xl shadow-gray-200/50 border border-gray-100 px-8 py-10 print:shadow-none print:border-none print:px-0 print:py-0"
                style={{ fontFamily: "'Courier New', Courier, monospace" }}
              >
                {/* Header */}
                <div className="flex flex-col items-center text-center mb-10 print:mb-4">
                  <span className="text-2xl font-normal text-gray-700 mb-4 print:text-black">
                    ₹
                  </span>
                  <h4 className="text-xl font-bold tracking-wide text-gray-900 mb-1 print:text-black">
                    JNMC PATHOLOGY
                  </h4>
                  <p className="text-xs text-gray-500 tracking-wide print:text-black">
                    Medical Road AMU, Aligarh
                  </p>
                </div>

                {/* Details */}
                <div className="space-y-3 border-t border-gray-200 pt-6 pb-6 text-xs text-gray-600 print:text-black print:border-black print:pt-4 print:pb-4">
                  <div className="flex justify-between">
                    <span>Date:</span>
                    <span className="text-gray-800 print:text-black">
                      {new Date(selectedBooking.createdAt).toLocaleString(
                        "en-IN",
                        {
                          day: "2-digit",
                          month: "2-digit",
                          year: "numeric",
                          hour: "2-digit",
                          minute: "2-digit",
                          hour12: true,
                        },
                      )}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span>Receipt No:</span>
                    <span className="text-gray-800 print:text-black">
                      #{selectedBooking.receiptNo}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span>Sample ID:</span>
                    <span className="text-gray-800 print:text-black">
                      #{selectedBooking.sampleId}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span>Coll. By:</span>
                    <span className="text-gray-800 print:text-black">
                      {selectedBooking.collectorName}
                    </span>
                  </div>
                  {selectedBooking.referringDoctor && (
                    <div className="flex justify-between">
                      <span>Ref. Doctor:</span>
                      <span className="text-gray-800 print:text-black">
                        {selectedBooking.referringDoctor.name}
                      </span>
                    </div>
                  )}
                </div>

                {/* Patient Info */}
                <div className="space-y-3 border-t border-gray-200 pt-6 pb-6 text-xs text-gray-600 print:text-black print:border-black print:pt-4 print:pb-4">
                  <div className="flex justify-between">
                    <span>Patient:</span>
                    <span className="text-gray-800 print:text-black">
                      {selectedBooking.patientName}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span>UHID:</span>
                    <span className="text-gray-800 print:text-black">
                      {selectedBooking.uhid || "Not Assigned"}
                    </span>
                  </div>
                </div>

                {/* Tests Table */}
                <div className="pt-6 pb-8 print:pt-4 print:pb-4">
                  <div className="flex justify-between text-[10px] font-bold uppercase tracking-widest text-gray-400 pb-4 print:text-black border-b border-transparent print:border-black mb-2">
                    <span>TEST DESCRIPTION</span>
                    <span>AMT</span>
                  </div>
                  <div className="space-y-4 print:space-y-2">
                    {selectedBooking.tests.map((test) => (
                      <div
                        key={test.testId || test._id}
                        className="flex justify-between text-xs text-gray-800 print:text-black"
                      >
                        <span>{test.testName}</span>
                        <span>{test.price.toFixed(2)}</span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Totals */}
                <div className="space-y-3 border-t border-gray-200 pt-6 pb-6 text-xs text-gray-600 print:text-black print:border-black print:pt-4 print:pb-4">
                  <div className="flex justify-between">
                    <span>Subtotal</span>
                    {/* Calculate subtotal from tests as legacy data might not have it separated */}
                    <span className="text-gray-800 print:text-black">
                      {selectedBooking.tests
                        .reduce((sum, t) => sum + t.price, 0)
                        .toFixed(2)}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span>Hospital Charges</span>
                    {/* Infer hospital charges */}
                    <span className="text-gray-800 print:text-black">
                      {(
                        selectedBooking.totalAmount -
                        selectedBooking.tests.reduce(
                          (sum, t) => sum + t.price,
                          0,
                        )
                      ).toFixed(2)}
                    </span>
                  </div>
                  <div className="flex justify-between pt-6 text-sm font-bold text-gray-900 print:text-black print:pt-4">
                    <span>TOTAL</span>
                    <span className="text-lg">
                      ₹ {selectedBooking.totalAmount.toFixed(2)}
                    </span>
                  </div>
                </div>

                {/* QR & Footer */}
                <div className="flex flex-col items-center pt-8 pb-4 print:pt-4 print:pb-0">
                  <QRCodeSVG
                    value={`https://jnmc.edu/reports/${selectedBooking._id}`}
                    size={80}
                    level="M"
                  />
                  <p className="text-[11px] text-gray-600 mt-4 font-medium print:text-black print:mt-2">
                    Scan to view report online
                  </p>
                  <p className="text-[10px] text-gray-400 mt-1 italic print:text-black">
                    Thank you for choosing JNMC
                  </p>
                </div>
              </div>
            )}

            {/* Label Layout */}
            {printMode === "label" && (
              <div className="bg-white rounded-none shadow-2xl shadow-gray-200/50 border border-gray-100 p-8 print:shadow-none print:border-none print:p-0 flex items-center justify-center">
                <div
                  className="w-[50mm] min-h-[25mm] border border-black p-1 box-border flex flex-col justify-between bg-white"
                  style={{ fontFamily: "Arial, sans-serif" }}
                >
                  <div className="flex justify-between items-start">
                    <div className="flex-1 overflow-hidden pr-1">
                      <p className="text-[10px] font-bold truncate leading-tight">
                        {selectedBooking.patientName || "Patient Name"}
                      </p>
                      <p className="text-[8px] font-semibold leading-tight">
                        UHID: {selectedBooking.uhid || "N/A"}
                      </p>
                      <p className="text-[8px] leading-tight">
                        {new Date().toLocaleDateString("en-IN")}
                      </p>
                    </div>
                    <div className="text-[9px] font-bold whitespace-nowrap">
                      {selectedBooking.sampleId || "S-ID"}
                    </div>
                  </div>

                  <div className="my-1 flex-1 overflow-hidden">
                    <p className="text-[7px] leading-tight break-words line-clamp-3">
                      {selectedBooking.tests.length > 0
                        ? selectedBooking.tests
                            .map((t) => t.testCode || t.testName)
                            .join(", ")
                        : "No Tests"}
                    </p>
                  </div>

                  <div className="flex justify-between items-end mt-1">
                    <div className="flex flex-col">
                      <span className="text-[7px] font-bold uppercase">-</span>
                      <span className="text-[6px] text-gray-500">
                        By: {selectedBooking.collectorName?.split(" ")[0]}
                      </span>
                    </div>
                    <QRCodeSVG
                      value={selectedBooking.sampleId || "Sample-ID"}
                      size={30}
                      level="L"
                    />
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
