"use client";

import React, { useState, useEffect, Suspense } from "react";
import {
  ArrowLeft,
  User,
  Fingerprint,
  Calendar,
  Droplets,
  Phone,
  Activity,
  Mail,
  MapPin,
  Info,
  UserPlus,
  GraduationCap,
  Briefcase,
  Loader2,
  CheckCircle,
} from "lucide-react";
import { useSearchParams, useRouter } from "next/navigation";
import {
  registerGeneralPatient,
  registerStudentPatient,
  registerEmployeePatient,
} from "@/lib/api";

function LoadingFallback() {
  return (
    <div className="flex items-center justify-center min-h-[60vh]">
      <Loader2 className="w-8 h-8 animate-spin text-gray-400" />
    </div>
  );
}

export default function CreatePatientAccount() {
  return (
    <Suspense fallback={<LoadingFallback />}>
      <CreatePatientAccountContent />
    </Suspense>
  );
}

function CreatePatientAccountContent() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const aadhaarParam = searchParams.get("aadhaar");

  const [patientType, setPatientType] = useState("General"); // 'General', 'Student', or 'Employee'
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");

  const [formData, setFormData] = useState({
    name: "",
    aadharNumber: aadhaarParam || "",
    dateOfBirth: "",
    gender: "",
    bloodGroup: "",
    phone: "",
    email: "",
    // Address fields
    address: "",
    dist: "", // for student
    city: "",
    state: "",
    pinCode: "",
    // Student specific
    uhid: "", // Will be auto-generated by backend if not provided, but frontend might need to send a dummy or let backend handle it.
    // Actually backend models say 'uhid' is required. Usually this is generated by system.
    // Let's assume we send a placeholder or the backend generates it.
    // Re-reading backend: models say required.
    // Let's generate a temporary random one or let user input if manual.
    // For now, I'll generate a random string to satisfy the model requirement if the backend doesn't geneate it.
    // uhid will be generated by backend
    uhid: "",

    // Student specific
    enrollmentNumber: "",
    facultyNumber: "",
    department: "",

    // Employee specific
    employeeId: "",
    pfNumber: "",
    designation: "",
    dateOfJoining: "",
  });

  useEffect(() => {
    if (aadhaarParam) {
      setFormData((prev) => ({
        ...prev,
        aadharNumber: aadhaarParam,
        name: searchParams.get("name") || prev.name,
        dateOfBirth: searchParams.get("dob") || prev.dateOfBirth,
        phone: searchParams.get("phone") || prev.phone,
        address: searchParams.get("address") || prev.address,
        city: searchParams.get("city") || prev.city,
        state: searchParams.get("state") || prev.state,
        pinCode: searchParams.get("pinCode") || prev.pinCode,
      }));
    }
  }, [searchParams, aadhaarParam]);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async () => {
    setIsLoading(true);
    setError("");
    setSuccess("");

    try {
      let response;
      if (patientType === "General") {
        // Prepare payload for General Patient
        const payload = {
          name: formData.name,
          // uhid generated by backend
          aadharNumber: formData.aadharNumber,
          dateOfBirth: formData.dateOfBirth,
          gender: formData.gender,
          bloodGroup: formData.bloodGroup,
          phone: formData.phone,
          email: formData.email,
          address: formData.address,
          city: formData.city,
          state: formData.state,
          pinCode: formData.pinCode,
        };
        response = await registerGeneralPatient(payload);
      } else if (patientType === "Student") {
        // Prepare payload for Student Patient
        const payload = {
          name: formData.name,
          // uhid generated by backend
          enrollmentNumber: formData.enrollmentNumber,
          facultyNumber: formData.facultyNumber,
          department: formData.department,
          gender: formData.gender,
          dateOfBirth: formData.dateOfBirth,
          bloodGroup: formData.bloodGroup,
          aadharNumber: formData.aadharNumber,
          phone: formData.phone,
          email: formData.email,
          address: {
            dist: formData.dist || formData.city, // Student model uses 'dist'
            city: formData.city,
            state: formData.state,
            pinCode: formData.pinCode,
          },
        };
        response = await registerStudentPatient(payload);
      } else if (patientType === "Employee") {
        // Prepare payload for Employee Patient
        const payload = {
          name: formData.name,
          employeeId: formData.employeeId,
          pfNumber: formData.pfNumber,
          department: formData.department,
          designation: formData.designation,
          dateOfJoining: formData.dateOfJoining,
          gender: formData.gender,
          dateOfBirth: formData.dateOfBirth,
          bloodGroup: formData.bloodGroup,
          aadharNumber: formData.aadharNumber,
          phone: formData.phone,
          email: formData.email,
          address: {
            dist: formData.dist || formData.city,
            city: formData.city,
            state: formData.state,
            pinCode: formData.pinCode,
          },
        };
        response = await registerEmployeePatient(payload);
      }

      setSuccess("Patient registered successfully!");
      // Optional: Redirect after delay
      setTimeout(() => {
        // The API wrapper returns the parsed JSON data directly, not the full axios/fetch response object.
        // So 'response' IS the data.
        const newPatient = response.patient;

        if (newPatient) {
          const params = new URLSearchParams({
            patientId: newPatient._id,
            name: newPatient.name,
            uhid: newPatient.uhid,
            phone: newPatient.phone || formData.phone,
            type: patientType,
          });
          router.push(`/lab/booking?${params.toString()}`);
        } else {
          console.error("Patient data missing in response", response);
          setError(
            "Registration successful, but failed to redirect. Please go to Patient Lookup.",
          );
        }
      }, 1500);
    } catch (err) {
      setError(err.message || "Registration failed");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="bg-[#F8FAFC] min-h-full font-sans text-slate-900">
      {/* Sidebar - Consistent with first screen */}

      {/* Main Content */}
      <div className="flex-1 p-12 overflow-y-auto">
        {/* Header */}
        <div className="flex items-start gap-6 mb-8">
          <button
            onClick={() => router.back()}
            className="p-2 hover:bg-slate-200 rounded-full transition-colors mt-1"
          >
            <ArrowLeft size={20} />
          </button>
          <div>
            <h2 className="text-2xl font-bold text-slate-900">
              Create Patient Account
            </h2>
            <p className="text-slate-500 text-sm">
              Complete the profile using Aadhaar verified details.
            </p>
          </div>
        </div>

        {/* Patient Type Selector */}
        <div className="max-w-4xl mx-auto mb-8">
          <div className="bg-[#EDF2F7] p-1.5 rounded-xl inline-flex w-full md:w-auto gap-1">
            {[
              { id: "General", icon: <User size={16} /> },
              { id: "Student", icon: <GraduationCap size={16} /> },
              { id: "Employee", icon: <Briefcase size={16} /> },
            ].map((type) => (
              <button
                key={type.id}
                onClick={() => setPatientType(type.id)}
                className={`flex items-center justify-center gap-2 px-8 py-2.5 rounded-lg text-sm font-semibold transition-all ${
                  patientType === type.id
                    ? "bg-white text-blue-600 shadow-sm"
                    : "text-slate-500 hover:text-slate-700"
                }`}
              >
                {type.icon} {type.id}
              </button>
            ))}
          </div>
        </div>

        {/* Form Card */}
        <div className="max-w-4xl mx-auto bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="p-10 space-y-8">
            {success && (
              <div className="bg-green-50 text-green-700 p-4 rounded-xl flex items-center gap-2">
                <CheckCircle size={20} />
                {success}
              </div>
            )}

            {error && (
              <div className="bg-red-50 text-red-700 p-4 rounded-xl">
                {error}
              </div>
            )}

            {/* Full Name */}
            <div className="space-y-2">
              <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wide">
                Full Name
              </label>
              <div className="relative">
                <User
                  className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"
                  size={18}
                />
                <input
                  type="text"
                  name="name"
                  value={formData.name}
                  onChange={handleInputChange}
                  placeholder="Enter full name"
                  className="w-full pl-12 pr-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none text-slate-700 font-medium"
                />
              </div>
            </div>

            {/* Student Specific Fields */}
            {patientType === "Student" && (
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="space-y-2">
                  <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wide">
                    Enrollment No.
                  </label>
                  <input
                    type="text"
                    name="enrollmentNumber"
                    value={formData.enrollmentNumber}
                    onChange={handleInputChange}
                    className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wide">
                    Faculty No.
                  </label>
                  <input
                    type="text"
                    name="facultyNumber"
                    value={formData.facultyNumber}
                    onChange={handleInputChange}
                    className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wide">
                    Department
                  </label>
                  <input
                    type="text"
                    name="department"
                    value={formData.department}
                    onChange={handleInputChange}
                    className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
                  />
                </div>
              </div>
            )}

            {/* Employee Specific Fields */}
            {patientType === "Employee" && (
              <>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wide">
                      Employee ID
                    </label>
                    <input
                      type="text"
                      name="employeeId"
                      value={formData.employeeId}
                      onChange={handleInputChange}
                      placeholder="e.g., EMP001"
                      className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
                    />
                  </div>
                  <div className="space-y-2">
                    <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wide">
                      PF Number
                    </label>
                    <input
                      type="text"
                      name="pfNumber"
                      value={formData.pfNumber}
                      onChange={handleInputChange}
                      placeholder="Provident Fund Number"
                      className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
                    />
                  </div>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  <div className="space-y-2">
                    <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wide">
                      Department
                    </label>
                    <input
                      type="text"
                      name="department"
                      value={formData.department}
                      onChange={handleInputChange}
                      placeholder="e.g., Radiology"
                      className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
                    />
                  </div>
                  <div className="space-y-2">
                    <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wide">
                      Designation
                    </label>
                    <input
                      type="text"
                      name="designation"
                      value={formData.designation}
                      onChange={handleInputChange}
                      placeholder="e.g., Lab Technician"
                      className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
                    />
                  </div>
                  <div className="space-y-2">
                    <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wide">
                      Date of Joining
                    </label>
                    <input
                      type="date"
                      name="dateOfJoining"
                      value={formData.dateOfJoining}
                      onChange={handleInputChange}
                      className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
                    />
                  </div>
                </div>
              </>
            )}

            {/* Row: Aadhaar & DOB */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wide">
                  Aadhaar Number
                </label>
                <div className="relative">
                  <Fingerprint
                    className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"
                    size={18}
                  />
                  <input
                    type="text"
                    name="aadharNumber"
                    value={formData.aadharNumber}
                    onChange={handleInputChange}
                    placeholder="12-digit Aadhaar"
                    className="w-full pl-12 pr-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none text-slate-700 font-medium"
                    readOnly={!!aadhaarParam}
                  />
                </div>
              </div>
              <div className="space-y-2">
                <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wide">
                  Date of Birth
                </label>
                <div className="relative">
                  <Calendar
                    className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"
                    size={18}
                  />
                  <input
                    type="date"
                    name="dateOfBirth"
                    value={formData.dateOfBirth}
                    onChange={handleInputChange}
                    className="w-full pl-12 pr-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none text-slate-700 font-medium"
                  />
                </div>
              </div>
            </div>

            {/* Row: Gender & Blood Group */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wide">
                  Gender
                </label>
                <select
                  name="gender"
                  value={formData.gender}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none appearance-none"
                >
                  <option value="">Select Gender</option>
                  <option value="Male">Male</option>
                  <option value="Female">Female</option>
                  <option value="Other">Other</option>
                </select>
              </div>
              <div className="space-y-2">
                <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wide">
                  Blood Group
                </label>
                <select
                  name="bloodGroup"
                  value={formData.bloodGroup}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none appearance-none"
                >
                  <option value="">Select Group</option>
                  <option value="A+">A+</option>
                  <option value="A-">A-</option>
                  <option value="B+">B+</option>
                  <option value="B-">B-</option>
                  <option value="AB+">AB+</option>
                  <option value="AB-">AB-</option>
                  <option value="O+">O+</option>
                  <option value="O-">O-</option>
                </select>
              </div>
            </div>

            {/* Row: Phone & Email */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wide">
                  Phone Number
                </label>
                <div className="relative">
                  <Phone
                    className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"
                    size={18}
                  />
                  <input
                    type="tel"
                    name="phone"
                    value={formData.phone}
                    onChange={handleInputChange}
                    placeholder="+91 00000 00000"
                    className="w-full pl-12 pr-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
                  />
                </div>
              </div>
              <div className="space-y-2">
                <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wide">
                  Email Address
                </label>
                <div className="relative">
                  <Mail
                    className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"
                    size={18}
                  />
                  <input
                    type="email"
                    name="email"
                    value={formData.email}
                    onChange={handleInputChange}
                    placeholder="email@example.com"
                    className="w-full pl-12 pr-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
                  />
                </div>
              </div>
            </div>

            {/* Address */}
            <div className="space-y-2">
              <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wide">
                Residential Address
              </label>
              <textarea
                name="address"
                value={formData.address}
                onChange={handleInputChange}
                rows="2"
                placeholder="Street address"
                className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none text-slate-600 resize-none"
              />
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="space-y-2">
                <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wide">
                  {patientType === "Student" ? "District" : "City"}
                </label>
                <input
                  type="text"
                  name={patientType === "Student" ? "dist" : "city"} // Handle field name diff
                  value={
                    patientType === "Student" ? formData.dist : formData.city
                  }
                  onChange={(e) => {
                    const val = e.target.value;
                    if (patientType === "Student")
                      setFormData((prev) => ({ ...prev, dist: val }));
                    else setFormData((prev) => ({ ...prev, city: val }));
                  }}
                  className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
                />
              </div>
              <div className="space-y-2">
                <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wide">
                  State
                </label>
                <input
                  type="text"
                  name="state"
                  value={formData.state}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
                />
              </div>
              <div className="space-y-2">
                <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wide">
                  Pin Code
                </label>
                <input
                  type="text"
                  name="pinCode"
                  value={formData.pinCode}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
                />
              </div>
            </div>
          </div>

          {/* Footer Actions */}
          <div className="px-10 py-6 bg-white border-t border-slate-100 flex items-center justify-between">
            <div className="flex items-center gap-2 text-[11px] text-slate-400 font-medium">
              <Info size={14} /> UHID:{" "}
              {formData.uhid || "Auto-generated upon registration"}
            </div>
            <div className="flex items-center gap-6">
              <button
                onClick={() => router.back()}
                className="text-sm font-bold text-slate-500 hover:text-slate-800 transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={handleSubmit}
                disabled={isLoading}
                className="bg-[#0F172A] text-white px-8 py-3.5 rounded-xl font-bold flex items-center gap-2 hover:bg-black transition-transform active:scale-95 shadow-lg shadow-slate-200 disabled:opacity-70"
              >
                {isLoading ? (
                  <>
                    <Loader2 className="animate-spin" size={18} /> Processing...
                  </>
                ) : (
                  <>
                    <UserPlus size={18} /> Create & Add Test
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
